<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <NuGetAudit>false</NuGetAudit>
    <RestoreSources>$(MSBuildThisFileDirectory)../../../packages</RestoreSources>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../Shared/Program.cs" Link="Program.cs" />
    <PackageReference Include="DM.DmProvider" Version="8.3.1.47463" />
  </ItemGroup>
</Project>
