<Project>
  <Import Project="$(MSBuildThisFileDirectory)../../Directory.Build.props"
          Condition="Exists('$(MSBuildThisFileDirectory)../../Directory.Build.props')" />
  <PropertyGroup>
    <BaseIntermediateOutputPath>$(MSBuildThisFileDirectory)obj/$(MSBuildProjectName)/</BaseIntermediateOutputPath>
    <MSBuildProjectExtensionsPath>$(BaseIntermediateOutputPath)</MSBuildProjectExtensionsPath>
  </PropertyGroup>
</Project>
