<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>DM.DmProvider</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>15.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup>
    <RootNamespace />
  </PropertyGroup>
  <ItemGroup>
    <None Remove="Dm.ReservedWords.txt" />
    <EmbeddedResource Include="Dm.ReservedWords.txt" LogicalName="Dm.ReservedWords.txt" />
  </ItemGroup>
  <ItemGroup />
</Project>